#1ª questão
library(vegan)
library(readr)
setwd("C:/Users/Edson Junior/OneDrive/Documentos/")
b<-read.table("riqueza.txt")
H<-diversity(b,"shannon")
Lambda<-diversity(b,"simpson")
Lambda
S<-specnumber(b)
Lambdai<-diversity(b, "invsimpson")
Eqhill<-Lambdai/exp(H)
fatores<-c(rep("A10",3),rep("A11",3),rep("A12",3),rep("A13",3),rep("A14",3),rep("A15",3),rep("A16",3))
tabela<-cbind(S,H,Lambda,equipelou,fatores)
tabela<-data.frame(tabela)
fator<-factor(fatores)
fator
tabela
boxplot(Lambda~fator,border="black",col="green",xlab = "locais",ylab = "H´",main="índices de diversidade de cada área")
bartlett.test(Lambda~fator,tabela)
r.anova=aov(Lambda~fator,tabela)
summary(r.anova)
boxplot(r.anova~fator)
boxplot(S~fator,border="black",col="yellow",xlab = "locais",ylab = "riqueza de espécies",main="diversidade alfa de cada área")
R.anova=aov(S~fator,tabela)
summary(R.anova)
boxplot(Eqhill~fator,border="black",col="red",xlab = "locais",ylab = "E´",main="índice de equitabilidade de cada área")
bartlett.test(Eqhill~fator,tabela)
r1.anova=aov(Lambda~fator,tabela)
summary(r.anova)

#2ª??? questão
B<-read.table("macrofauna.txt")
B
h<-diversity(B,"shannon")
lambda<-diversity(B,'simpson')
s<-specnumber(B)
Equipielou<-diversity(B, "invsimpson")
eqhill<-Equipielou/exp(H)
Fatores<-c(rep("superior",6),rep("médio",6),rep("inferior",30))
Fatores
Tabela<-cbind(s,h,lambda,Equipielou,Fatores)
Tabela<-data.frame(Tabela)
Tabela
Fator<-factor(Fatores)
Fator
boxplot(lambda~Fator,border="black",col="green",xlab = "locais",ylab = "H´",main="índices de diversidade de cada setor")
bartlett.test(lambda~Fator,Tabela)
R.anova=aov(lambda~Fator,Tabela)
summary(R.anova)
T.Teste<-TukeyHSD(R.anova)
plot(T.Teste)
boxplot(s~Fator,border="black",col="yellow",xlab = "locais",ylab = "S",main="riqueza de espécies de cada setor")
bartlett.test(s~Fator,Tabela)
R2.anova=aov(s~Fator,Tabela)
summary(R2.anova)
T2.Teste<-TukeyHSD(R2.anova)
plot(T2.Teste)
boxplot(eqhill~Fator,border="black",col="red",xlab = "locais",ylab = "E´",main="equitabilidade de cada setor")
bartlett.test(eqhill~Fator,Tabela)
R3.anova=aov(eqhill~Fator,Tabela)
summary(R3.anova)
T3.Teste<-TukeyHSD(R3.anova)
plot(T3.Teste)


#3ª??? questão
f<-read.table("floresta.txt")
F<-t(f)
H3<-diversity(F,"shannon")
D<-diversity(F,"simpson")
S3<-specnumber(F)
EQUIPIELOU<-diversity(F, "invsimpson")
EQHILL<-EQUIPIELOU/exp(H3)
FATORES<-c(rep("avançado",5),rep("inferior",5),rep("médio",5))
TABELA<-cbind(S3,H3,D,EQHILL,FATORES)
TABELA<-data.frame(TABELA)
FATOR<-factor(FATORES)
boxplot(D~FATOR,border="black",col="green",xlab = "locais",ylab = "D",main="índices de diversidade de cada setor")
bartlett.test(D~FATOR,TABELA)
R1.ANOVA=aov(D~FATOR,Tabela)
summary(R1.ANOVA)
T1.TESTE<-TukeyHSD(R1.ANOVA)
plot(T1.TESTE)
boxplot(S3~FATOR,border="black",col="yellow",xlab = "locais",ylab = "S",main="índices de riqueza de cada setor")
bartlett.test(S3~FATOR,Tabela)
R2.ANOVA=aov(S3~FATOR,Tabela)
summary(R2.ANOVA)
T2.TESTE<-TukeyHSD(R2.ANOVA)
plot(T2.TESTE)
boxplot(EQHILL~FATOR,border="black",col="red",xlab = "locais",ylab = "E´",main="índices de riqueza de cada setor")
bartlett.test(EQHILL~FATOR,Tabela)
R3.ANOVA=aov(EQHILL~FATOR,Tabela)
summary(R3.ANOVA)
T3.TESTE<-TukeyHSD(R3.ANOVA)
plot(T3.TESTE)
