#1? quest?o
library(vegan)
library(readr)
setwd("C:/Users/Edson Junior/OneDrive/Documentos/")
Regioes<-read.table("macrofauna.txt")
Regioes
head(Regioes,40)
Hill1<-renyi(Regioes, hill=TRUE)
Hill1
write.csv(Hill1, file = "hill.csv",row.names=TRUE)
SerHill1<-data.frame(Hill1)
attach(SerHill1)
Amostras1<-c(rep("superior",12),rep("m?dio",18),rep("inferior",12))
Fator1<-factor(Amostras1)
boxplot(X0~Fator1,border="black",col="green",las=1, xlab="regi?es", ylab="q=0", cex=1.4,cex.lab=1.4,cex.axis=1.2, main="S?rie de Hill X0")
bartlett.test(X0~Fator1,SerHill1)
R1.ANOVA1<-aov(X0~Fator1,SerHill1)
summary(R1.ANOVA1)
R1TESTE1<-TukeyHSD(R1.ANOVA1)
plot(R1TESTE1)
kruskal.test(X0~Fator1,SerHill1)
boxplot(X1~Fator1,border="black",col="yellow",las=1, xlab="regi?es", ylab="q=1", cex=1.4,cex.lab=1.4,cex.axis=1.2,main="S?rie de Hill X1")
bartlett.test(X1~Fator1,SerHill1)
kruskal.test(X1~Fator1,SerHill1)
R1.ANOVA2<-aov(X1~Fator1,SerHill1)
summary(R1.ANOVA2)
R1TESTE2<-TukeyHSD(R1.ANOVA2)
plot(R1TESTE2)
boxplot(X2~Fator1,border="black",col="red",las=1, xlab="regi?es", ylab="q=2", cex=1.4,cex.lab=1.4,cex.axis=1.2,main="S?rie de Hill X2")
bartlett.test(X1~Fator1,SerHill1)
kruskal.test(X2~Fator1,SerHill1)
R1.ANOVA3<-aov(X2~Fator1,SerHill1)
summary(R1.ANOVA3)
R1TESTE3<-TukeyHSD(R1.ANOVA3)
plot(R1TESTE3)

#2? quest?o
library(vegan)
library(readr)
setwd("C:/Users/Edson Junior/OneDrive/Documentos/")
areas<-read.table("FlorestaTot.txt")
Areas<-t(areas)
head(Areas)
Hill2<-renyi(Areas,hill=TRUE)
write.csv(Hill2, file = "hill.csv",row.names=TRUE)
SerHill2<-data.frame(Hill2)
attach(SerHill2)
Amostras2<-c(rep("avan?ado",1),rep("inferior",1),rep("m?dio",1))
Fator2<-factor(Amostras2)
barplot(X0~Fator2,border="black",col="green",las=1, xlab="?reas", ylab="q=0", cex=1.4,cex.lab=1.4,cex.axis=1.2, main="S?rie de Hill X0",ylim=c(0,60))
bartlett.test(X0~Fator2,SerHill2)
R2.ANOVA1<-aov(X0~Fator2,SerHill2)
summary(R2.ANOVA1)
R2TESTE1<-TukeyHSD(R2.ANOVA1)
plot(R2TESTE1)
barplot(X1~Fator2,border="black",col="yellow",las=1, xlab="?reas", ylab="q=1", cex=1.4,cex.lab=1.4,cex.axis=1.2, main="S?rie de Hill X1",ylim=c(0,35))
bartlett.test(X1~Fator2,SerHill2)
R2.ANOVA2<-aov(X1~Fator2,SerHill2)
summary(R2.ANOVA2)
R2TESTE2<-TukeyHSD(R2.ANOVA2)
plot(R2TESTE2)
barplot(X2~Fator2,border="black",col="red",las=1, xlab="?reas", ylab="q=2", cex=1.4,cex.lab=1.4,cex.axis=1.2, main="S?rie de Hill X2",ylim=c(0,25))
bartlett.test(X2~Fator2,SerHill2)
R2.ANOVA3<-aov(X2~Fator2,SerHill2)
summary(R2.ANOVA3)
R2TESTE3<-TukeyHSD(R2.ANOVA3)
plot(R2TESTE3)

#3? quest?o
library(vegan)
library(readr)
setwd("C:/Users/Edson Junior/OneDrive/Documentos/")
estacoes<-read.table("Esta??es.txt")
Estacoes<-t(estacoes)
head(Estacoes,2)
Hill3<-renyi(Estacoes, hill=TRUE)
write.csv(Hill3, file = "hill.csv",row.names=TRUE)
SerHill3<-data.frame(Hill3)
attach(SerHill3)
Amostra3<-c(rep("1",1),rep("22",1),rep("42",1),rep("62",1),rep("82",1))
Fator3<-factor(Amostra3)
barplot(X0~Fator3,border="black",col="green",las=1, xlab="esta??es", ylab="q=0", cex=1.4,cex.lab=1.4,cex.axis=1.2,ylim=c(0,10),main="S?rie de Hill X0",)
R3ANOVA1<-aov(X0~Fator3,SerHill3)
summary(R3.ANOVA1)
R3TESTE1<-TukeyHSD(R3.ANOVA1)
plot(R3TESTE1)
barplot(X2~Fator3,border='black',col="green",las=1, xlab="esta??es", ylab="q=2", cex=1.4,cex.lab=1.4,cex.axis=1.2,ylim=c(0,10),main="S?rie de Hill X2")
R3.ANOVA2<-aov(X2~Fator3,SerHill3)
summary(R3.ANOVA2)
R3TESTE2<-TukeyHSD(R3.ANOVA2)
plot(R3TESTE2)


