library(vegan)
library(FD)
library(readr)
library(sads)
library(devtools)
setwd("G:/Meu Drive/R")

#diversidade PI
av<-read.table("avaliação 1.txt",header = TRUE)
Av<-t(av)
H<-diversity(Av,"shannon")
Eq>0.8
D<-(1-(diversity(Av,"simpson")))
S<-specnumber(Av)
Eq<-D/exp(H)
Fatores1<-c(rep("9",47),rep("8",29),rep("7",19),rep("3",63),rep("2",27),rep("5",25),rep("6",31),rep("4",17),rep("1",19))
tabela<-cbind(S,H,D,Eq,Fatores1)
tabela<-data.frame(tabela)
fator<-factor(Fatores1)
fator
tabela
boxplot(H~fator,border="black",col="green",xlab = "áreas",ylab = "H´",main="Índice de Diversidade de Shannon",ylim=c(0,3.0))
R1.anova1=aov(H~fator,tabela)
summary(R1.anova1)
T1.Tk1<-TukeyHSD(R1.anova1)
plot(T1.Tk1,cex.axis=0.531)
boxplot(D~fator,border="black",col="yellow",xlab = "áreas",ylab = "D",main="Índice de Diversidade de Ginni-Simpson",ylim=c(0.0,1.0))
R1.anova2=aov(D~fator,tabela)
summary(R1.anova2)
T1.Tk2<-TukeyHSD(R1.anova2)
plot(T1.Tk2,cex.axis=0.531)
boxplot(S~fator,border="black",col="red",xlab = "áreas",ylab = "S",main="Índice de Diversidade Alfa",ylim=c(0,35))
R1.anova3=aov(S~fator,tabela)
summary(R1.anova3)
T1.Tk3<-TukeyHSD(R1.anova3)
plot(T1.Tk3,cex.axis=0.531)
boxplot(Eq~fator,border="black",col="lightblue",xlab = "áreas",ylab = "E´",main="Índice de Equitabilidade de Hill",ylim=c(0,1))
R1.anova4=aov(Eq~fator,tabela)
summary(R1.anova4)
T1.Tk4<-TukeyHSD(R1.anova4)
plot(T1.Tk4,cex.axis=0.531)

#Séries de Hill
Hill<-renyi(Av, hill=TRUE)
write.csv(Hill, file = "hill.csv",row.names=TRUE)
SerHill<-data.frame(Hill)
attach(SerHill)
Fatores2<-c(rep("9",47),rep("8",29),rep("7",19),rep("3",63),rep("2",27),rep("5",25),rep("6",31),rep("4",17),rep("1",19))
Fator1<-factor(Fatores2)
boxplot(X1~Fator1,border="black",col="green",las=1, xlab="Áreas", ylab="q=1", cex=1.4,cex.lab=1.4,cex.axis=1.2, main="Série de Hill X1",ylim=c(0,20))
R2.ANOVA2<-aov(X1~Fator1,SerHill)
summary(R2.ANOVA2)
R2TESTE2<-TukeyHSD(R2.ANOVA2)
plot(R2TESTE2,cex.axis=0.531)
boxplot(X2~Fator1,border="black",col="yellow",las=1, xlab="Áreas", ylab="q=2", cex=1.4,cex.lab=1.4,cex.axis=1.2, main="Série de Hill X2",ylim=c(0,15))
R2.ANOVA3<-aov(X2~Fator1,SerHill)
summary(R2.ANOVA3)
R2TESTE3<-TukeyHSD(R2.ANOVA3)
plot(R2TESTE3,cex.axis=0.531)

#SAD
estAv<-read.table("SADAv.1.txt",header = TRUE)
EstAv<-data.frame(estAv)
EstAv<-EstAv[order(EstAv$Soma, decreasing = TRUE),]
LogEstAv<- octav(EstAv$Soma)
plot(LogEstAv)
plot(LogEstAv, prop = TRUE, border=NA, col=NA)
lines(LogEstAv, mid = FALSE, prop = TRUE, col="red")
legend("topright", c("espécies` macro"), col=c("red"), lty=1)
Rank<-rad(EstAv$Soma)
plot(Rank, ylab="Número de indivíduos")
Avls <- fitsad(EstAv$Soma, "ls")
summary(Avls)
coef(Avls)
logLik(Avls)
AIC(Avls)
AvPerfilGram<-profile(Avls)
likelregions(AvPerfilGram)
confint(AvPerfilGram)
plotprofmle(AvPerfilGram)
plot(AvPerfilGram)  
plot(Avls ,which=1)
plot(Avls ,which=2)
plot(Avls ,which=3)
plot(Avls ,which=4)
Avpl <- fitsad(EstAv$Soma, sad="poilog")
summary(Avpl)
Avln <- fitsad(EstAv$Soma, sad="lnorm", trunc=0.5)
summary(Avln)
AICtab(Avls,Avpl, Avln, base=TRUE)
Avhist.ls<- octavpred(Avls)
Avhist.pl<-octavpred(Avpl)
Avhist.ln<-octavpred(Avln)
plot(LogEstAv,border="black",col="lightgreen",ylab="abundância",xlab="classes", main="SAD das pradarias")+
  lines(Avhist.ls, col="green")+
  lines(Avhist.pl, col="blue")+
  lines(Avhist.ln, col="red")+
  legend("topright",c("modelo logarítimico","modelo lognormal","modelo lognormal- truncada"),col=c("green","blue","red"),lty = 1)
Avhistrad.ls<- radpred(Avls)
Avhistrad.pl<-radpred(Avpl)
Avhistrad.ln<-radpred(Avln)
plot(Rank,ylab="abundância",xlab="rank", main="RAD das pradarias")+
  lines(Avhistrad.ls, col="green")+
  lines(Avhistrad.pl, col="blue")+
  lines(Avhistrad.ln, col="red")+
  legend("topright",c("modelo logarítimico","modelo lognormal","modelo lognormal- truncada"),col=c("green","blue","red"),lty = 1)
